apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-deployment

spec:
  replicas: 5

  selector:
    matchLabels:
      app: hello

  template:
    metadata:
      labels:
        app: hello

    spec:
      containers:
      - name: hello-container
        image: hello-k8s:v1
        imagePullPolicy: Never

        ports:
        - containerPort: 8080